version: 2
jobs:
  build:
    docker:
            - image: continuumio/miniconda3
    environment:
            ANACONDA: "$HOME/anaconda3"
            DISTRIB: "$HOME/anaconda3/bin/conda"

    steps:
      - checkout
      - run:
           name: install miniconda
           command: |
                   #cd /home/circleci
             #export MINICONDA=$HOME/miniconda
             #export PATH="$MINICONDA/bin:$PATH"
             #hash -r
             #wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
             #bash miniconda.sh -b -f -p $MINICONDA
             #conda config --set always_yes yes
             #conda update conda
             #conda info -a
             #conda create -n testenv python=3.6.0
             #source activate testenv
             # - run:
             #name: Create HTML
          #    command: make
      #- run:
          #name: Start local docker cluster
          #command: graphcool local up
      #- run:
          #name: Run tests
#command: docker run -it --network container:a77d5a5e2299 -v $PWD:/ node bash test.sh
