version: 2
jobs:
  build:
    docker:
            - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
           name: Create environment
           command: |
                   python3 -m venv venv
                   . venv/bin/activate
                   pip install -r requirements.txt
      - run:
          name: Start local docker cluster
          command: |
                . venv/bin/activate
                jupyter-nbconvert --execute Example.ipynb
      #- run:
          #name: Run tests
#command: docker run -it --network container:a77d5a5e2299 -v $PWD:/ node bash test.sh
